# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149fSHR6VjOJ7hRNo_BnL8xmJu2nafgW4
"""

def kasallik_tashxisi(belgi):
  if belgi == "tish og'rig'i":
    return "trimol iching"
  elif belgi == "bosh og'rig'i":
    return "bolnol iching"
  elif belgi == "allergiya":
    return "diazolin iching"
  elif belgi == "gripp":
    return "taylol hot iching"
  elif belgi == "ko'z og'rig'i":
    return "tetraskilin maz surting"
  elif belgi == "oyoq og'rig'i":
    return "qupen iching"
  elif belgi == "oshqozon og'rig'i":
    return "noshpa iching"
  elif belgi == "isitma":
    return "parasetamol iching"
  elif belgi == "bel og'rig'i":
    return "indometatsin maz surting"
  elif belgi == "shikastlanish":
      return "shifokorga murojat qiling"
  else:
    return "Shifokorga murojat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)

def tibbiyot_sohasidagi_mutaxassislar(belgi):
  if belgi == "stomologiya":
    return "1-qavat 3-xona"
  elif belgi == "nevropotolog":
    return "2-qavat 9-xona"
  elif belgi == "xirurg":
    return "1-qavat 6-xona"
  elif belgi == "dietolog":
    return "2-qavat 8-xona"
  elif belgi == "okulist":
    return "2-qavat 15-xona"
  elif belgi == "jarrox":
      return "1-qavat 4-xona"
belgi=input("Kerakli mutaxassisni kiriting")
natija=tibbiyot_sohasidagi_mutaxassislar(belgi)
print(natija)